name = "gestion-proyecto-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
vars = { ENVIRONMENT = "production" }

[env.production]
route = "https://api.tudominio.com/*"
zone_id = "tu_zone_id"

[env.development]
vars = { ENVIRONMENT = "development" }

[build]
command = "npm install"
cwd = "./"

[[d1_databases]]
binding = "DB"
database_name = "proyecto"
database_id = "tu_database_id"

[env.production.d1_databases]
binding = "DB"
database_name = "proyecto"
database_id = "tu_production_id"
